changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - bug
    - title: Maintenance
      labels:
        - maintenance
    - title: Other Changes
      labels:
        - "*"
