name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-2025, windows-2022, windows-2019, windows-11-arm]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Check tests
        run: deno task test
      - name: Check build
        run: deno task build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Check format
        run: deno task fmt:check
