name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Cache Zig
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            .zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
            ${{ runner.os }}-zig-
      - name: Setup Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.16.0
      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          cache: true

      - name: Check format
        run: deno task fmt:check
      - name: Check tests
        run: deno task test
      - name: Check release
        run: deno task release
