name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Cache Zig
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            .zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
            ${{ runner.os }}-zig-
      - name: Setup Zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.15.2
      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          cache: true

      - name: Check format
        run: deno task fmt:check
      - name: Check tests
        run: deno task test
      - name: Check release
        run: deno task release
