name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache Zig
        uses: actions/cache@v5
        with:
          path: |
            .zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
            ${{ runner.os }}-zig-
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Setup Deno
        run: npm i -g deno

      - name: Check format
        run: deno task fmt:check
      - name: Check tests
        run: deno task test
      - name: Check release
        run: deno task release
