name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  CI:
    strategy:
      matrix:
        os: [windows-2025, windows-2022]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Zig
        uses: actions/cache@v4
        with:
          path: |
            .zig-cache
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig.zon') }}
            ${{ runner.os }}-zig-
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Check format
        run: deno task fmt:check
      - name: Check tests
        run: deno task test
      - name: Check release
        run: deno task release
