name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: Ryuapp.Rb
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }}
